### ISSUE TITLE
Log messages from sampler

### ISSUE THREAD

**Issue by patrik93** [johanneswuerbach/jaeger-dynamodb#42]
Hi there @johanneswuerbach !

First of all thanks for your effort to build this plugin. I have a question tho, is it possible (if yes, how) to get rid of the items added to the dynamodb jaeger.spans table, like the following?
`{ "internal.span.format" : { "S" : "proto" }, "component" : { "S" : "gRPC" }, "hostname" : { "S" : "jaeger" }, "jaeger.version" : { "S" : "Go-2.29.1" }, "span.kind" : { "S" : "client" }, "sampler.type" : { "S" : "const" }, "sampler.param" : { "S" : "true" }, "ip" : { "S" : "172.21.0.3" }, "client-uuid" : { "S" : ... }, ... }`

I did not set the GRPC_STORAGE_PLUGIN_LOG_LEVEL that means my log level is warn (by default). This creates with this log level around 5 new every seconds. 

In addition, what is the purpose of the Lambda function in the project? I have the following error on the DynamoDB stream details/triggers tab in the AWS console: `PROBLEM: Function call failed` but my traces from the HOTROD stored to the DB anyways.

Thanks in advance!

**Comment by johanneswuerbach** [comment]
Hey, those spans are logged internally by jaeger and are expected and can be used to troubleshoot jaeger search or ingestion performance. Any particular reason why you would like to remove them?

The `GRPC_STORAGE_PLUGIN_LOG_LEVEL` only configures what the plugin itself is logging to stdout. Do you see logs every 5s or spans/traces?

The lambda function is building the service dependency graph from the ingested traces, did you actually create it? If yes, you should see more details in the AWS Lambda Console and the logs of the created function. Currently the lambda is created by default, but I guess this should be configurable.

**Comment by patrik93** [comment]
Hey,

The reason I don't want to have them is the cost. In one hour it created 10,480 items in the table. I found in the jaegerUI from the service jaeger-query service there are spans every 2 seconds with the name /jaeger.storage.v1.SpanWriterPlugin/WriteSpan

`
Tags
component: gRPC
internal.span.format:proto
sampler.param:true
sampler.type:const
span.kind: client
`

`GRPC_STORAGE_PLUGIN_LOG_LEVEL` is clear now, thanks. Previously with the "debug" level which is in the repo it created 14 gigabytes in around 8 hours. 

Re: lambda function
I have downloaded your released lambda-dependency.zip and run the terraform which created every resources what was mentioned in it.

**Comment by johanneswuerbach** [comment]
It looks like you can disable tracing for jaeger itself already in the operator https://github.com/jaegertracing/jaeger-operator/blob/91e3b69ee5c8761bbda9d3cf431400a73fc1112a/apis/v1/jaeger_types.go#L247

Could you test whether this removes those spans?

**Comment by patrik93** [comment]
I can verify adding `JAEGER_DISABLED=true` to environment variables disables the spans on `jaeger.storage.v1.SpanWriterPlugin/WriteSpan`. Thanks for your help!

How do you accept contributions tho? I have added some fixes to the terraform in the readme for myself and I would be happy if I can help you work with that - even if its small -  contribution.

**Comment by johanneswuerbach** [comment]
Pull requests are definitely welcome. The plugin is currently still being tested at my current workplace so brushing up the documentation wasn't the main priority yet, but any help here is welcome.

**Comment by patrik93** [comment]
Thanks for your effort and help one more time. I'm going to create that in the next few days. I'm going to close this issue.
